/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IPL_2022_BIG_SCREEN;

/**
 *
 * @author PRODUCTION-STUDIO-10
 */


public class First_Innings_Output extends javax.swing.JFrame {

    /**
     * Creates new form First_Innings_Output
     */
    public First_Innings_Output() {
        initComponents();
        
        this.setSize(1024,768);
        this.jLabel104.setVisible(false);
//        this.runRate_lable.setVisible(false);
        
      //  this.setBounds(0, 0, 1024, 768);
      //  new FirstInningsRefresh();
      //  new TCPClient1();
       
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        team_name_lable = new javax.swing.JLabel();
        powerplay_lable = new javax.swing.JLabel();
        review_lable1 = new javax.swing.JLabel();
        reviewTeam1_Name = new javax.swing.JLabel();
        reviewValue1_lable = new javax.swing.JLabel();
        reviewTeam2_Name = new javax.swing.JLabel();
        reviewValue2_lable = new javax.swing.JLabel();
        total_score_wkt_lable = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        tot_Overs_lable = new javax.swing.JLabel();
        striker1_lable = new javax.swing.JLabel();
        striker2_lable = new javax.swing.JLabel();
        batsman1_name = new javax.swing.JLabel();
        batsman2_name = new javax.swing.JLabel();
        batsman1_runs = new javax.swing.JLabel();
        batsman2_runs = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bowler_name = new javax.swing.JLabel();
        bowler_over_lable = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        background_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(null);

        time.setFont(new java.awt.Font("AlineaIncise", 1, 50)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("00:00");
        jPanel1.add(time);
        time.setBounds(400, 20, 250, 70);

        team_name_lable.setFont(new java.awt.Font("AlineaIncise", 1, 130)); // NOI18N
        team_name_lable.setForeground(new java.awt.Color(255, 255, 255));
        team_name_lable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        team_name_lable.setText("KIIVP");
        jPanel1.add(team_name_lable);
        team_name_lable.setBounds(30, 0, 410, 150);

        powerplay_lable.setFont(new java.awt.Font("AlineaIncise", 1, 40)); // NOI18N
        powerplay_lable.setForeground(new java.awt.Color(255, 255, 255));
        powerplay_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(powerplay_lable);
        powerplay_lable.setBounds(370, 80, 290, 70);

        review_lable1.setFont(new java.awt.Font("AlineaIncise", 1, 34)); // NOI18N
        review_lable1.setForeground(new java.awt.Color(25, 57, 138));
        review_lable1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        review_lable1.setText("REVIEW");
        jPanel1.add(review_lable1);
        review_lable1.setBounds(660, 50, 140, 90);

        reviewTeam1_Name.setFont(new java.awt.Font("AlineaIncise", 1, 30)); // NOI18N
        reviewTeam1_Name.setForeground(new java.awt.Color(255, 255, 255));
        reviewTeam1_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reviewTeam1_Name.setText("PBKS");
        jPanel1.add(reviewTeam1_Name);
        reviewTeam1_Name.setBounds(800, 50, 100, 40);

        reviewValue1_lable.setFont(new java.awt.Font("AlineaIncise", 1, 45)); // NOI18N
        reviewValue1_lable.setForeground(new java.awt.Color(255, 255, 255));
        reviewValue1_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reviewValue1_lable.setText("1");
        jPanel1.add(reviewValue1_lable);
        reviewValue1_lable.setBounds(810, 80, 80, 60);

        reviewTeam2_Name.setFont(new java.awt.Font("AlineaIncise", 1, 30)); // NOI18N
        reviewTeam2_Name.setForeground(new java.awt.Color(255, 255, 255));
        reviewTeam2_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reviewTeam2_Name.setText("PBKS");
        jPanel1.add(reviewTeam2_Name);
        reviewTeam2_Name.setBounds(900, 50, 90, 40);

        reviewValue2_lable.setFont(new java.awt.Font("AlineaIncise", 1, 45)); // NOI18N
        reviewValue2_lable.setForeground(new java.awt.Color(255, 255, 255));
        reviewValue2_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reviewValue2_lable.setText("1");
        jPanel1.add(reviewValue2_lable);
        reviewValue2_lable.setBounds(910, 80, 80, 60);

        total_score_wkt_lable.setFont(new java.awt.Font("AlineaIncise", 1, 126)); // NOI18N
        total_score_wkt_lable.setForeground(new java.awt.Color(255, 255, 255));
        total_score_wkt_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_score_wkt_lable.setText("999/10");
        jPanel1.add(total_score_wkt_lable);
        total_score_wkt_lable.setBounds(40, 150, 500, 210);

        jLabel104.setFont(new java.awt.Font("Futura", 1, 54)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(255, 255, 255));
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel104.setText("RUN RATE");
        jPanel1.add(jLabel104);
        jLabel104.setBounds(1230, 240, 160, 90);

        tot_Overs_lable.setFont(new java.awt.Font("AlineaIncise", 1, 90)); // NOI18N
        tot_Overs_lable.setForeground(new java.awt.Color(255, 255, 255));
        tot_Overs_lable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tot_Overs_lable.setText("19.6");
        jPanel1.add(tot_Overs_lable);
        tot_Overs_lable.setBounds(780, 150, 210, 200);

        striker1_lable.setFont(new java.awt.Font("AlineaIncise", 1, 60)); // NOI18N
        striker1_lable.setForeground(new java.awt.Color(255, 255, 255));
        striker1_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        striker1_lable.setText("*");
        jPanel1.add(striker1_lable);
        striker1_lable.setBounds(40, 360, 40, 80);

        striker2_lable.setFont(new java.awt.Font("AlineaIncise", 1, 60)); // NOI18N
        striker2_lable.setForeground(new java.awt.Color(255, 255, 255));
        striker2_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        striker2_lable.setText("*");
        jPanel1.add(striker2_lable);
        striker2_lable.setBounds(40, 490, 40, 80);

        batsman1_name.setFont(new java.awt.Font("AlineaIncise", 1, 60)); // NOI18N
        batsman1_name.setForeground(new java.awt.Color(255, 255, 255));
        batsman1_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        batsman1_name.setText("CHAKRAVARTHY");
        jPanel1.add(batsman1_name);
        batsman1_name.setBounds(80, 360, 600, 120);

        batsman2_name.setFont(new java.awt.Font("AlineaIncise", 1, 60)); // NOI18N
        batsman2_name.setForeground(new java.awt.Color(255, 255, 255));
        batsman2_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        batsman2_name.setText("CHAKRAVARTHY");
        jPanel1.add(batsman2_name);
        batsman2_name.setBounds(80, 490, 590, 120);

        batsman1_runs.setFont(new java.awt.Font("AlineaIncise", 1, 60)); // NOI18N
        batsman1_runs.setForeground(new java.awt.Color(25, 57, 138));
        batsman1_runs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        batsman1_runs.setText("999(999)");
        batsman1_runs.setToolTipText("");
        jPanel1.add(batsman1_runs);
        batsman1_runs.setBounds(690, 360, 300, 120);

        batsman2_runs.setFont(new java.awt.Font("AlineaIncise", 1, 60)); // NOI18N
        batsman2_runs.setForeground(new java.awt.Color(25, 57, 138));
        batsman2_runs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        batsman2_runs.setText("999(999)");
        batsman2_runs.setToolTipText("");
        jPanel1.add(batsman2_runs);
        batsman2_runs.setBounds(680, 490, 310, 120);

        jLabel32.setFont(new java.awt.Font("Futura", 0, 60)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel32);
        jLabel32.setBounds(850, 435, 30, 70);

        jLabel33.setFont(new java.awt.Font("Futura", 0, 60)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel33);
        jLabel33.setBounds(1000, 435, 30, 70);

        jLabel28.setFont(new java.awt.Font("Futura", 0, 60)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel28);
        jLabel28.setBounds(1000, 535, 30, 70);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(800, 80, 190, 0);

        bowler_name.setFont(new java.awt.Font("AlineaIncise", 1, 55)); // NOI18N
        bowler_name.setForeground(new java.awt.Color(255, 255, 255));
        bowler_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bowler_name.setText("CHAKRAVATHY");
        jPanel1.add(bowler_name);
        bowler_name.setBounds(50, 610, 490, 120);

        bowler_over_lable.setFont(new java.awt.Font("AlineaIncise", 1, 50)); // NOI18N
        bowler_over_lable.setForeground(new java.awt.Color(255, 255, 255));
        bowler_over_lable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bowler_over_lable.setText("4.5 - 4 - 999 - 10");
        jPanel1.add(bowler_over_lable);
        bowler_over_lable.setBounds(490, 610, 500, 120);

        jLabel6.setFont(new java.awt.Font("AlineaIncise", 1, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("OVERS -");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(510, 150, 270, 200);

        background_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg_images/SB Template 1st Innings Template.jpg"))); // NOI18N
        jPanel1.add(background_Label);
        background_Label.setBounds(0, 0, 1024, 768);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First_Innings_Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First_Innings_Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First_Innings_Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First_Innings_Output.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_Innings_Output();
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel background_Label;
    public static javax.swing.JLabel batsman1_name;
    public static javax.swing.JLabel batsman1_runs;
    public static javax.swing.JLabel batsman2_name;
    public static javax.swing.JLabel batsman2_runs;
    public static javax.swing.JLabel bowler_name;
    public static javax.swing.JLabel bowler_over_lable;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel104;
    public static javax.swing.JLabel jLabel28;
    public static javax.swing.JLabel jLabel32;
    public static javax.swing.JLabel jLabel33;
    public static javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel powerplay_lable;
    public static javax.swing.JLabel reviewTeam1_Name;
    public static javax.swing.JLabel reviewTeam2_Name;
    public static javax.swing.JLabel reviewValue1_lable;
    public static javax.swing.JLabel reviewValue2_lable;
    public static javax.swing.JLabel review_lable1;
    public static javax.swing.JLabel striker1_lable;
    public static javax.swing.JLabel striker2_lable;
    public static javax.swing.JLabel team_name_lable;
    public static javax.swing.JLabel time;
    public static javax.swing.JLabel tot_Overs_lable;
    public static javax.swing.JLabel total_score_wkt_lable;
    // End of variables declaration//GEN-END:variables
}
