/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RENT;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.plaf.basic.BasicLookAndFeel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public static String[] sqlcredentials;
    public static String username = "root", pwd = "root";
    public static Connection con = null;
    private static final String DRIVER_NAME = "com.mysql.cj.jdbc.Driver";
    private static String DB_URL = "jdbc:mysql://localhost:3306/";
    private static String DB_NAME = "rent_data";
    public static Object[] row;

    public main() {
        initComponents();

        individual_floor_data.setVisible(false);
        ADD_RENT_PANEL.setVisible(false);
        tot_rent.setVisible(false);

        jTable1.getTableHeader().setPreferredSize(new Dimension(100, 30));
        jTable1.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 16));
        {
            jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    c.setBackground(row % 2 == 0 ? new Color(235, 52, 207) : new Color(255, 204, 255));

                    return c;
                }
            });

        }
        addTableData();
    }

    public static Connection getConnection() {

        try {
            if (con == null) {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection(DB_URL + DB_NAME, username, pwd);
            }
        } catch (Exception e) {
            System.err.println("Username or password for DB Connection is incorrect!!!");
            e.printStackTrace();
        } finally {
            return con;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Home_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ADD_RENT_PANEL = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        individual_floor_data = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        tot_rent = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        RENTTXT = new javax.swing.JTextField();
        floorTXT = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ADD_RENT_BUTTON = new javax.swing.JButton();
        TOT_RENT_BUTTON = new javax.swing.JButton();
        BILL_GEN_BTN1 = new javax.swing.JButton();
        background_label1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        background_label2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        background_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DEEPAK RENT ADDING SYSTEM V2.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 100, 70));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RENT DETAILS");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 70));

        jLabel1.setFont(new java.awt.Font("AlineaIncise", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 90));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1155, 70));

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 0));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home_Panel.setBackground(new java.awt.Color(204, 255, 255));
        Home_Panel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 102)));
        Home_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("AlineaIncise", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "FLOOR", "RENT", "DATE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Home_Panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 660, 350));

        ADD_RENT_PANEL.setBackground(new java.awt.Color(255, 204, 255));
        ADD_RENT_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "ADD RENT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AlineaIncise", 1, 14))); // NOI18N
        ADD_RENT_PANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("AlineaIncise", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT FLOOR", "GROUND", "1ST LEFT", "1ST RIGHT", "2ND LEFT", "2ND RIGHT", "TOP" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        ADD_RENT_PANEL.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 140, 30));

        jLabel51.setFont(new java.awt.Font("AlineaIncise", 1, 14)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("DATE:");
        ADD_RENT_PANEL.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 30));

        jLabel48.setFont(new java.awt.Font("AlineaIncise", 1, 14)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("RENT:");
        ADD_RENT_PANEL.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));
        ADD_RENT_PANEL.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 150, 50));

        jButton1.setFont(new java.awt.Font("AlineaIncise", 1, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ADD_RENT_PANEL.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        jLabel55.setFont(new java.awt.Font("AlineaIncise", 1, 14)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("FLOOR:");
        ADD_RENT_PANEL.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("CLOSE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        ADD_RENT_PANEL.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 70, -1));
        ADD_RENT_PANEL.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 150, -1));

        Home_Panel.add(ADD_RENT_PANEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 50, 440, 180));

        individual_floor_data.setBackground(new java.awt.Color(255, 204, 255));
        individual_floor_data.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "BILL GENERATE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AlineaIncise", 1, 14))); // NOI18N
        individual_floor_data.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setFont(new java.awt.Font("AlineaIncise", 0, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT FLOOR", "GROUND ", "1ST LEFT", "1ST RIGHT", "2ND LEFT", "2ND RIGHT", "TOP" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        individual_floor_data.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 170, 30));

        jButton4.setFont(new java.awt.Font("AlineaIncise", 1, 12)); // NOI18N
        jButton4.setText("GENERATE BILL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        individual_floor_data.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel54.setFont(new java.awt.Font("AlineaIncise", 1, 14)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("DATE:");
        individual_floor_data.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 80, 30));

        jLabel56.setFont(new java.awt.Font("AlineaIncise", 1, 14)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("FLOOR:");
        individual_floor_data.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 80, 30));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setText("CLOSE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        individual_floor_data.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 70, -1));
        individual_floor_data.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        Home_Panel.add(individual_floor_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 50, 440, 180));

        tot_rent.setBackground(new java.awt.Color(255, 204, 255));
        tot_rent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "TOTAL RENT CALCULATOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AlineaIncise", 1, 14))); // NOI18N
        tot_rent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("AlineaIncise", 1, 12)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("TOTAL MONEY RECEVIED TILL DATE");
        tot_rent.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 230, 40));

        jLabel49.setBackground(new java.awt.Color(102, 255, 255));
        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel49.setOpaque(true);
        tot_rent.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 170, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("CHECK TOTAL ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        tot_rent.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 170, 40));

        jComboBox3.setFont(new java.awt.Font("AlineaIncise", 0, 11)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT FLOOR", "GROUND ", "1ST LEFT", "1ST RIGHT", "2ND LEFT", "2ND RIGHT", "TOP" }));
        tot_rent.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText("CLOSE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        tot_rent.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 70, -1));

        Home_Panel.add(tot_rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 50, 440, 180));

        jButton3.setFont(new java.awt.Font("AlineaIncise", 1, 12)); // NOI18N
        jButton3.setText("DELETE ROWS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Home_Panel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 150, 35));

        jButton5.setFont(new java.awt.Font("AlineaIncise", 1, 12)); // NOI18N
        jButton5.setText("CLEAR TABLE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Home_Panel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 150, 35));

        jLabel52.setFont(new java.awt.Font("AlineaIncise", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("DATE :");
        Home_Panel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 360, 100, 30));

        jLabel57.setFont(new java.awt.Font("AlineaIncise", 1, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("FLOOR:");
        Home_Panel.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 280, 100, 30));

        RENTTXT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RENTTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Home_Panel.add(RENTTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 150, 30));

        floorTXT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        floorTXT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Home_Panel.add(floorTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, 30));

        jButton6.setFont(new java.awt.Font("AlineaIncise", 1, 12)); // NOI18N
        jButton6.setText("REFRESH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Home_Panel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 150, 35));

        jLabel58.setFont(new java.awt.Font("AlineaIncise", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("RENT:");
        Home_Panel.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 320, 100, 30));

        datetxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        datetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Home_Panel.add(datetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 120, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT FLOOR", "GROUND", "1ST LEFT", "1ST RIGHT", "2ND LEFT", "2ND RIGHT", "TOP", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        Home_Panel.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 140, 30));

        jLabel2.setFont(new java.awt.Font("AlineaIncise", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SEARCH");
        Home_Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 400, 100, 30));

        ADD_RENT_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ADD_RENT_BUTTON.setText("ADD RENT");
        ADD_RENT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD_RENT_BUTTONActionPerformed(evt);
            }
        });
        Home_Panel.add(ADD_RENT_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 5, 150, 35));

        TOT_RENT_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TOT_RENT_BUTTON.setText("RENT CALCULATOR");
        TOT_RENT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOT_RENT_BUTTONActionPerformed(evt);
            }
        });
        Home_Panel.add(TOT_RENT_BUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 5, 150, 35));

        BILL_GEN_BTN1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BILL_GEN_BTN1.setText("GENERATE BILL");
        BILL_GEN_BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BILL_GEN_BTN1ActionPerformed(evt);
            }
        });
        Home_Panel.add(BILL_GEN_BTN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 5, 150, 35));
        Home_Panel.add(background_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 670));

        jPanel1.add(Home_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 670));

        jTabbedPane1.addTab("HOME", jPanel1);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CEO: DEEPAK YADAV R");
        jLabel4.setOpaque(true);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 410, 30));

        jLabel6.setBackground(new java.awt.Color(255, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("EMAIL: deepakyadav.ica@gmail.com");
        jLabel6.setOpaque(true);
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 410, 30));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 130, 150));
        jPanel4.add(background_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 670));

        jTabbedPane1.addTab("ABOUT", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONTACT: 9110677852");
        jLabel5.setOpaque(true);
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 260, 30));
        jPanel5.add(background_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 670));

        jTabbedPane1.addTab("CONTACT", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1160, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String FLOOR = jComboBox3.getSelectedItem().toString().trim();

//        jLabel50.setText(FLOOR.toString());
        //        Statement st;
        try {
            Statement st = getConnection().createStatement();
            String query = "SELECT SUM(RENT)as sumrent FROM rent_details WHERE FLOOR = '" + FLOOR + "'";
            System.out.println(query);
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                String sum = rs.getString("sumrent");
                System.out.println(sum);
                if (sum == null) {
                    JOptionPane.showMessageDialog(rootPane, "data no found");
                    jLabel49.setText("00.00");
                } else {
                    jLabel49.setText(sum);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String rent = jTextField1.getText();
        Date date = jDateChooser1.getDate();
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
        } else {
            SimpleDateFormat dt1 = new SimpleDateFormat("dd-MM-yyyy");
            String datefinal = dt1.format(date);
            Object FLOOR = jComboBox1.getSelectedItem().toString();

            if (rent.isEmpty() || jDateChooser1.getDate() == null || FLOOR.equals("SELECT FLOOR")) {

                JOptionPane.showMessageDialog(this, "Please enter all fields");

            } else {
                try {
                    Statement st = getConnection().createStatement();
                    //("query executed");
                    String query = "insert into rent_details(FLOOR,RENT,date)values('" + FLOOR + "','" + rent + "','" + datefinal + "')";

                    st.executeUpdate(query);

                    JOptionPane.showMessageDialog(null, "Data Stored Successfully");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        addTableData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String o = jComboBox2.getSelectedItem().toString().trim();
        System.out.println(o);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Connection con = getConnection();

        for (int i = model.getRowCount() - 1; i >= 0; i--) {

            model.removeRow(i);
        }
        Statement st;
        ResultSet res;
        try {

            st = con.createStatement();
            String query = "SELECT * FROM rent_details WHERE FLOOR = '" + o + "'";
            System.out.println(query);
            res = st.executeQuery(query);

            while (res.next()) {

                Object[] row = new Object[jTable1.getColumnCount()];

                row[0] = res.getString("FLOOR");
                row[1] = res.getString("RENT");
                row[2] = res.getString("DATE");

                model.addRow(row);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here
        String o = jComboBox2.getSelectedItem().toString().trim();
        System.out.println(o);
        Date date = jDateChooser2.getDate();
        if (date == null || o.equals("SELECT FLOOR")) {
            JOptionPane.showMessageDialog(this, "Please enter all fields");
        } else {

            SimpleDateFormat dt1 = new SimpleDateFormat("dd-MM-yyyy");
            String datef = dt1.format(date);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            Connection con = getConnection();

            for (int i = model.getRowCount() - 1; i >= 0; i--) {

                model.removeRow(i);
            }
            Statement st;
            ResultSet res;
            try {

                st = con.createStatement();
                String query1 = "SELECT * FROM rent_details WHERE FLOOR = '" + o + "' AND date = '" + datef + "' ";
                System.out.println(query1);
                res = st.executeQuery(query1);
                if (res.next()) {
                    System.out.println("found");
                    row = new Object[jTable1.getColumnCount()];

                    row[0] = res.getString("FLOOR");
                    row[1] = res.getString("RENT");
                    row[2] = res.getString("DATE");
                    System.out.println("-----------------------" + row[2]);

                    model.addRow(row);

                    FileOutputStream fo1 = new FileOutputStream("bill_details/bill.txt");
                    System.out.println("success bill generated");
                    Desktop desktop = Desktop.getDesktop();
                    Font myFont = new Font("Alinealncise", Font.BOLD, 12);
                    fo1.write(("⚜⚜SHRI NILAYA⚜⚜\n" + "--------------------------------------\n"
                            + "FLOOR: " + row[0] + "\n--------------------------------------\n"
                            + "RENT: " + row[1] + "\n--------------------------------------\n" + "DATE: " + row[2]
                            + "\n--------------------------------------\n" + "FINAL RENT TO PAY\n--------------------------------------\n" + row[1]).getBytes());
                    fo1.write("/- RUPEES ONLY\n---------------END-----------------\n".getBytes());
                    File file = new File("bill_details/bill.txt");
                    if (file.exists()) {
                        desktop.open(file);
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "bill not found on selected date");
                }

//            while (res.next()) {
//
//                row = new Object[jTable1.getColumnCount()];
//
//                row[0] = res.getString("FLOOR");
//                row[1] = res.getString("RENT");
//                row[2] = res.getString("DATE");
//                System.out.println("-----------------------" + row[2]);
//
//                model.addRow(row);
//
//            }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(rootPane, "please select row to delete");
            return;
        }
        String floor = floorTXT.getText().trim();
        String date = datetxt.getText().trim();
        int result = JOptionPane.showConfirmDialog(null, "Sure? You want to delete?", "all data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {

            Statement st;

            if (floor.isEmpty()) {

                JOptionPane.showMessageDialog(null, "Please Select the rows");

            } else {
                try {
                    st = getConnection().createStatement();

                    String query = "DELETE FROM rent_details WHERE FLOOR='" + floor + "' and date='" + date + "'";

                    st.execute(query);
                    model.removeRow(i);

                } catch (Exception e) {
                    e.printStackTrace();
                }
                JOptionPane.showMessageDialog(null, "Query deleted successfully");
                floorTXT.setText("");
                RENTTXT.setText("");
                datetxt.setText("");
                addTableData();
            }
        }
        if (result == JOptionPane.NO_OPTION) {
            return;
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTable1.setSelectionBackground(Color.blue);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int selectedIndexColumn = jTable1.getSelectedRow();

        floorTXT.setText(model.getValueAt(selectedIndexColumn, 0).toString());
        RENTTXT.setText(model.getValueAt(selectedIndexColumn, 1).toString());
        datetxt.setText(model.getValueAt(selectedIndexColumn, 2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        addTableData();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Statement st;
        int result = JOptionPane.showConfirmDialog(null, "Sure? You want to delete?", "all data",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {

            try {
                st = getConnection().createStatement();

                String query = "DELETE FROM rent_details";

                st.executeUpdate(query);
                addTableData();

            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Query deleted successfully");
        }
        if (result == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        Object o = jComboBox4.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        for (int i = model.getRowCount() - 1; i >= 0; i--) {

            model.removeRow(i);
        }
        Connection con = getConnection();

        Statement st;
        ResultSet res;
        try {

            st = con.createStatement();
            String query = "SELECT * FROM rent_details WHERE FLOOR=" + "'" + o + "'";

            res = st.executeQuery(query);

            while (res.next()) {

                Object[] row = new Object[jTable1.getColumnCount()];

                row[0] = res.getString("FLOOR");
                row[1] = res.getString("RENT");
                row[2] = res.getString("DATE");

                model.addRow(row);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void BILL_GEN_BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BILL_GEN_BTN1ActionPerformed
        // TODO add your handling code here:
        individual_floor_data.setVisible(true);
        ADD_RENT_PANEL.setVisible(false);
        tot_rent.setVisible(false);
    }//GEN-LAST:event_BILL_GEN_BTN1ActionPerformed

    private void ADD_RENT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD_RENT_BUTTONActionPerformed
        // TODO add your handling code here:
        individual_floor_data.setVisible(false);
        ADD_RENT_PANEL.setVisible(true);
        tot_rent.setVisible(false);
    }//GEN-LAST:event_ADD_RENT_BUTTONActionPerformed

    private void TOT_RENT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOT_RENT_BUTTONActionPerformed
        // TODO add your handling code here:
        individual_floor_data.setVisible(false);
        ADD_RENT_PANEL.setVisible(false);
        tot_rent.setVisible(true);
    }//GEN-LAST:event_TOT_RENT_BUTTONActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ADD_RENT_PANEL.setVisible(false);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        tot_rent.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        individual_floor_data.setVisible(false);

    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADD_RENT_BUTTON;
    private javax.swing.JPanel ADD_RENT_PANEL;
    private javax.swing.JButton BILL_GEN_BTN1;
    private javax.swing.JPanel Home_Panel;
    private javax.swing.JTextField RENTTXT;
    private javax.swing.JButton TOT_RENT_BUTTON;
    private javax.swing.JLabel background_label;
    private javax.swing.JLabel background_label1;
    private javax.swing.JLabel background_label2;
    private javax.swing.JTextField datetxt;
    private javax.swing.JTextField floorTXT;
    private javax.swing.JPanel individual_floor_data;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel tot_rent;
    // End of variables declaration//GEN-END:variables
public void addTableData() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        Connection con = getConnection();

        for (int i = model.getRowCount() - 1; i >= 0; i--) {

            model.removeRow(i);
        }
        Statement st;
        ResultSet res;
        try {

            st = con.createStatement();
            String query = "SELECT * FROM rent_details";

            res = st.executeQuery(query);

            while (res.next()) {

                Object[] row = new Object[jTable1.getColumnCount()];

                row[0] = res.getString("FLOOR");
                row[1] = res.getString("RENT");
                row[2] = res.getString("DATE");

                model.addRow(row);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
